### ISSUE TITLE
Apparent small bug impacting lateral boundary processing of winds

### ISSUE THREAD

**Issue by MatthewPyle-NOAA** [NOAA-GFDL/GFDL_atmos_cubed_sphere#169] opened 2022-01-18 14:49 UTC
**Describe the bug**
Using the relatively new pressure tendency diagnostic, we’ve noticed a [slight, transient increase in domain-averaged surface pressure tendency at the frequency of lateral boundary updates in limited-area runs](https://www.emc.ncep.noaa.gov/users/emc.campara/rrfs/cyc/ptend/images/ptend_lam_tm00.png).  This behavior was traced to the definition of reg_bc_update_time in dyn_core.F90 routine prior to regional_boundary_update calls for the w/u/v variables.  

The increased noise seen with the original line:

reg_bc_update_time=current_time_in_seconds+bdt*(n_map-1)+**it***dt

goes away when reg_bc_update_time is made more similar to other definitions of this variable:

reg_bc_update_time=current_time_in_seconds+bdt*(n_map-1)+(**it-1**)*dt

It also seems like this reg_bc_update_time variable is being defined in a suboptimal portion of the code, and should be shifted out of the #ifndef SW_DYNAMICS block surrounding the 'w' update.  

**To Reproduce**
Run the latest UFS weather model with print_diff_pgr = .true. within &gfs_physics_nml

**Expected behavior**
No increase in noise around boundary update times.  A comparison [without ](https://www.emc.ncep.noaa.gov/mmb/mpyle/ctrlchart.png)and [with ](https://www.emc.ncep.noaa.gov/mmb/mpyle/testchart.png)the proposed modification.

**System Environment**
Should be system independent.

**Additional context**
Slides 1-5 of [this presentation](https://docs.google.com/presentation/d/1NbVsIXweJkma2yDKFBsZksFG0MU6k6enc8wg5fQk84c/edit?usp=sharing) provides a bit more detail

**Comment by lharris4** [comment] 2022-01-19 14:49
Hi, Matt. Thank you for your very nice bug report. 

After discussion with @kaiyuan-cheng I believe there is a bug in the regional updating, but this would not fix it. All of the BC calls made in dyn_core() after the forward-in-time update d_sw() need to be made at the `it` timelevel, not the `it-1` timelevel. Currently the BCs for the pressure variables (assigned by nh_bc()) and u,v,w use the right timelevel:
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/c885c3e7d05f960c3aaa5074246eb0c5aefb81dc/model/dyn_core.F90#L942
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/c885c3e7d05f960c3aaa5074246eb0c5aefb81dc/model/dyn_core.F90#L1148-L1162
whereas pt, delp, and q_con do *not* use the right timelevel:
https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/blob/c885c3e7d05f960c3aaa5074246eb0c5aefb81dc/model/dyn_core.F90#L852-L871

Compare to the nested grid code, which uses the right timelevel for all of these variables. A future update to the code should re-write the regional BC code to use the same routines as the nested-grid BCs.

It is true that the reg_bc_update_time assignment needs to be made *outside* of the #ifndef block, and also outside of the `if (.not. hydrostatic)` block.

**Comment by MatthewPyle-NOAA** [comment] 2022-01-19 16:21
Thanks for the feedback.   I'm sure you are correct about what it should be from a science perspective.   But the it*dt term for u and v winds fools the logic in the boundary code for the final acoustic step before fresh boundary information is ingested (believes it is at the beginning of the period rather than at the end).   I had an earlier fix for the issue that would adjust the fraction_interval variable if it had been reset for an acoustic step > 1.   This approach touched more routines as "it" needed to be added as a subroutine argument in various places for it to be available down in the regional boundary processing code.  But would this approach be a more viable fix from your perspective?

      if (fraction_interval .eq. 0.0 .and. it .gt. 1) then
        fraction_interval=1.0
      endif

**Comment by lharris4** [comment] 2022-01-19 19:47
Hi, Matt. I don't understand; is this some problem in the regional BC
module? In that case, the root cause of the problem should be fixed,
instead of adding code to dyn_core.F90.

Thanks,
Lucas

**Comment by MatthewPyle-NOAA** [comment] 2022-01-19 21:54
Hi Lucas,

The actual fix can be made in the regional BC module (the conditional redefinition of fraction_interval in my comment above), but it requires knowing the value of the acoustic timestep (it) down in that code.  I got it down there by adding it as an argument passed in the subroutine call to regional_boundary_update.   Several source codes have regional_boundary_update calls, so superficial changes are made in several places to support fixing it in this way.   Perhaps there is a more elegant way to achieve the same result.  

-Matt

**Comment by lharris4** [comment] 2022-01-24 17:19
OK. Please let me know when an MR is available so we can review it.

Thanks,
Lucas

**Comment by MatthewPyle-NOAA** [comment] 2022-01-25 17:20
Hi Lucas,

So far I've been working to add these changes on top of the "main" branch code in my fork.  Is that the proper approach?  Thus far I’ve been struggling to get this atmos_cubed_sphere code compiled within the latest UFS weather model, but I’m a bit out of my element.  Just want to make sure I shouldn’t be trying to work the change into “gfdl_test” or some other branch of atmos_cubed_sphere.  

Thanks,

Matt

**Comment by MatthewPyle-NOAA** [comment] 2022-01-25 17:26
Thanks for the quick response, Rusty.  I will pivot to dev/emc.

**Closed** 2022-02-25 20:21 UTC
